[build]
    base = "/"
    publish= "public"
    command="gatsby build"

[functions]
    directory = "functions"

[dev]
    command = "gatsby develop"

[[plugins]]
    package = "@netlify/plugin-gatsby"
